version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      - run:
          name: Install aws  
          command: |
            # echo "installing aws cli"
            # wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip"
            # unzip awscliv2.zip
            # chmod +x ./aws/install
            # # sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
            # sudo ./aws/install  
            # echo "installed aws cli"
      - run:
          name: Install aws  
          command: |
            # aws --version 
            docker version

      - run:
          name: Build JAR
          command: ./mvnw package
      - run:
          name: Build Docker image
          command: |
            docker build -t api-service .
            docker tag api-service:latest ${ECR_REPOSITORY_URI}/api-service:latest
            docker build -t  api-service:${CIRCLE_SHA1} .
            docker tag  api-service:${CIRCLE_SHA1} /api-service:${CIRCLE_SHA1}
      - run:
          name: Push Docker image to ECR
          command: |
            $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            docker push ${ECR_REPOSITORY_URI}/api-service:latest
            docker push ${ECR_REPOSITORY_URI}/api-service:${CIRCLE_SHA1}	
