version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - run:
          name: Build JAR
          command: ./mvnw package
      - run:
          name: Build Docker image
          command: |
            docker build -t api-service .
            docker tag api-service:latest ${ECR_REPOSITORY_URI}/api-service:latest
            docker build -t  api-service:${CIRCLE_SHA1} .
            docker tag  api-service:${CIRCLE_SHA1} /api-service:${CIRCLE_SHA1}
      - run:
          name: Push Docker image to ECR
          command: |
            $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            docker push ${ECR_REPOSITORY_URI}/api-service:latest
            docker push ${ECR_REPOSITORY_URI}/api-service:${CIRCLE_SHA1}	
